// Browser check: Agent settings → Flight intake (rig). node --env-file=.env.rig rig/intake/settings-check.mjs
import { chromium } from "playwright";
let failures = 0; const ok = (c, w, d = "") => { console.log(`${c ? "PASS" : "FAIL"}  ${w}${d ? `  · ${d}` : ""}`); if (!c) failures += 1; };
const db = async (p) => (await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/rest/v1/${p}`, { headers: { apikey: process.env.SUPABASE_SERVICE_ROLE_KEY, authorization: `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}` } })).json();
const ADDR = `ops-desk-${Date.now().toString(36)}@clearway.example`;
const b = await chromium.launch(); const p = await (await b.newContext({ viewport: { width: 1366, height: 1000 } })).newPage();
const errors = []; p.on("pageerror", (e) => errors.push(e.message)); p.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
await p.goto("http://127.0.0.1:3999/agent/settings", { waitUntil: "load" }); await p.waitForTimeout(3500);
const card = p.locator('section[aria-label="Flight intake"]');
ok(await card.count() === 1, "Flight intake card on Agent settings");
const field = card.getByLabel("Add to Send intake emails to");
await field.focus(); await p.keyboard.type("not-an-email"); await p.keyboard.press("Enter"); await p.waitForTimeout(200);
ok(await card.getByText("Not an email address: not-an-email").count() > 0, "bad address refused in the page");
await field.fill(""); await p.keyboard.type(ADDR); await p.keyboard.press("Enter");
await p.keyboard.press("Tab"); await p.keyboard.press("Tab"); await p.waitForTimeout(100);
const focused = await p.evaluate(() => document.activeElement?.textContent);
await card.locator("div", { has: p.getByText("Send intake emails to", { exact: true }) }).getByRole("button", { name: "Save" }).last().click();
await p.waitForTimeout(1500);
await p.screenshot({ path: "rig/.scratch/shots/settings-intake.png", fullPage: true });
await p.reload({ waitUntil: "load" }); await p.waitForTimeout(3500);
ok(await card.getByText(ADDR).count() > 0, "saved address still there after reload");
ok(await card.getByText(/Saved .* by rig-test@rig.invalid/).count() > 0, "shows who saved it");
const row = (await db("agent_settings?select=reason&id=eq.intake:notify_to"))[0];
ok(row?.reason?.includes(ADDR), "stored in agent_settings, not the .env", row?.reason);
const ov = await (await fetch("http://127.0.0.1:5175/api/mailbox/overview")).json();
ok(ov.notifyTo.includes(ADDR), "the agent uses it for intake emails", ov.notifyTo.join(", "));
const audit = await db("agent_audit_log?select=detail&kind=eq.settings.changed&order=created_at.desc&limit=1");
ok(JSON.stringify(audit[0]?.detail ?? {}).includes("notifyTo"), "change is in the audit log");
const bad = await p.evaluate(() => [...document.querySelectorAll('section[aria-label="Flight intake"] select, section[aria-label="Flight intake"] [title], section[aria-label="Flight intake"] input:not([type=text])')].length);
ok(bad === 0, "no native select / title tooltip / non-text input in the card");
ok(await p.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), "no horizontal scroll");
ok(errors.length === 0, "console clean", errors.slice(0, 2).join(" | "));
void focused; await b.close(); console.log(failures ? `${failures} FAILED` : "ALL PASSED"); process.exit(failures ? 1 : 0);
