"use client";

import { C } from "../ui/tokens";

// /agent/doc — the viewer on its own page, for hosts that cannot overlay it
// (the wall console frames the panel; a citation there hands off here). Opens
// with the panel closed and "Ask about this document" in the header.

import { useEffect } from "react";
import { useSearchParams } from "next/navigation";
import PortalShell from "@/components/portal/Shell";
import { fetchDocRef, useViewer } from "./ViewerContext";
import type { DocRef } from "./types";

function Opener() {
  const params = useSearchParams();
  const v = useViewer();
  useEffect(() => {
    const source = params.get("source") as DocRef["source"] | null; const id = params.get("id"); if (!source || !id) return;
    const page = Number(params.get("page") || 0) || null; const span = params.get("span");
    (async () => {
      let ref: DocRef | null = null;
      if (source === "knowledge" || source === "generated" || source === "attachment") ref = await fetchDocRef(source, id);
      // AIP / GEN by ICAO (`source=aip&id=EVRA`): the agent resolves the cached copy and its revision.
      if ((source === "aip" || (source as string) === "gen") && /^[A-Za-z0-9]{4}$/.test(id)) ref = await fetchDocRef(source as "aip" | "gen", id.toUpperCase());
      // Metadata answers 404 for a file that is not yours: open anyway with what the link says, so the
      // viewer shows the permission card with the file name (§V9) instead of nothing.
      if (!ref && (source === "generated" || source === "attachment")) {
        const filename = params.get("filename") ?? "document";
        const base = source === "generated" ? `/agent/api/files/${id}` : `/agent/api/attachments/${id}`;
        ref = { key: `${source}:${id}`, source, id, filename, mime: filename.toLowerCase().endsWith(".pdf") ? "application/pdf" : null, bytes: null, url: `${base}?inline=1`, downloadUrl: base, sourceUrl: null, tier: source === "generated" ? "internal" : "attachment", sourceName: source === "generated" ? "Generated by the agent" : "Attachment" };
      }
      if (!ref && source === "aip") { const url = params.get("url") ?? `${id}?inline=1`; const filename = params.get("filename") ?? id.split("/").pop() ?? "document.pdf"; ref = { key: `aip:${id}`, source: "aip", id, filename, mime: "application/pdf", bytes: null, url, downloadUrl: id, sourceUrl: id, tier: "internal", sourceName: "AIP Portal" }; }
      // `bytes` lets a link state the size when the metadata has none (e.g. a hand-off link); the viewer's size limit reads it.
      if (ref && params.get("bytes")) ref = { ...ref, bytes: Number(params.get("bytes")) || ref.bytes };
      if (ref) v.openDocument(ref, { page, panelClosed: true, from: "Chat", citation: span ? (params.get("verbatim") === "1" ? { k: 1, page, span: null, verbatim: { text: span, recordId: params.get("record") } } : { k: 1, page, span, revision: params.get("citedRevision") ? { state: "superseded", label: String(params.get("citedRevision")), revision: String(params.get("citedRevision")) } : null }) : null });
    })();
  }, [params]); // eslint-disable-line react-hooks/exhaustive-deps
  return <div style={{ padding: 32, fontSize: 14, color: C.muted }}>{v.open ? "" : "Opening the document…"}</div>;
}

export default function StandaloneDocument() {
  return <PortalShell crumb="Ops Agent" title="Document" subtitle="Opened from the wall console." footer={false}><Opener /></PortalShell>;
}
