"use client";

// One way in for the five entry points (§V3): resolve what was clicked into a
// DocRef and open it — in the viewer when the shell hosts one, in a new
// browser tab for Web citations, and via the standalone /agent/doc route when
// the panel runs inside another app's iframe (the wall console).

import { useCallback } from "react";
import type { DocumentData, FileData, SourceRef, TableData, VerbatimRecord } from "../types";
import { aipDocRef, fetchDocRef, useViewerOptional } from "./ViewerContext";
import type { Citation, DocRef, OpenOptions } from "./types";

function inIframe() { return typeof window !== "undefined" && window.parent !== window; }

export function useOpenDocument(from?: string | null) {
  const viewer = useViewerOptional();

  const openRef = useCallback((ref: DocRef, opts: OpenOptions = {}) => {
    if (viewer) { viewer.openDocument(ref, { from: from ?? opts.from ?? null, ...opts }); return; }
    // No viewer host here (the panel is framed by the wall console): hand off to the portal's standalone viewer.
    const q = new URLSearchParams({ source: ref.source, id: ref.id, filename: ref.filename });
    if (opts.page ?? opts.citation?.page) q.set("page", String(opts.page ?? opts.citation?.page));
    if (ref.url) q.set("url", ref.url);
    if (opts.citation?.span) q.set("span", opts.citation.span.slice(0, 800));
    const url = `/agent/doc?${q.toString()}`;
    if (inIframe()) window.parent.postMessage({ type: "cw-agent-open-doc", url }, window.location.origin); else window.open(url, "_blank", "noopener");
  }, [viewer, from]);

  /** §V3 E1 — a document result card. */
  const openDocumentResult = useCallback(async (doc: DocumentData, opener?: HTMLElement | null) => {
    if (doc.documentId) { const ref = await fetchDocRef("knowledge", doc.documentId); if (ref) openRef(ref, { opener }); return; }
    if (doc.href) openRef(aipDocRef(doc.href, doc.title, { cached: doc.cached, source: doc.subtitle }), { opener });
  }, [openRef]);

  /** §V3 E2 — a generated file. */
  const openGenerated = useCallback(async (file: FileData, opener?: HTMLElement | null) => {
    const ref = await fetchDocRef("generated", file.id);
    openRef(ref ?? { key: `generated:${file.id}`, source: "generated", id: file.id, filename: file.filename, mime: file.mime, bytes: file.bytes, url: `${file.downloadPath}?inline=1`, downloadUrl: file.downloadPath, sourceUrl: null, tier: "internal", sourceName: "Generated by the agent", fetchedAt: file.generatedAt ?? null }, { opener });
  }, [openRef]);

  /** §V3 E3 — an attachment the user sent. */
  const openAttachment = useCallback(async (id: string, name: string, opener?: HTMLElement | null) => {
    const ref = await fetchDocRef("attachment", id);
    if (ref) openRef(ref, { opener }); else openRef({ key: `attachment:${id}`, source: "attachment", id, filename: name, mime: null, bytes: null, url: `/agent/api/attachments/${id}?inline=1`, downloadUrl: `/agent/api/attachments/${id}`, sourceUrl: null, tier: "attachment", sourceName: "Attachment" }, { opener });
  }, [openRef]);

  /** §V3 E4 — a citation. Web sources open the URL; file sources open at the passage. Returns false when nothing openable. */
  const openCitation = useCallback(async (s: SourceRef, conversationId: string | null, opener?: HTMLElement | null): Promise<boolean> => {
    if (s.tier === "web") { if (s.href) window.open(s.href, "_blank", "noopener"); return Boolean(s.href); }
    const citation: Citation = { k: s.n, page: s.page ?? null, span: s.span ?? null, conversationId };
    if (s.documentSource === "knowledge" && s.documentId) { const ref = await fetchDocRef("knowledge", s.documentId); if (!ref) return false; openRef(ref, { citation, opener }); return true; }
    if (s.documentSource === "aip" && s.documentPath) { openRef(aipDocRef(s.documentPath, s.label), { citation, opener }); return true; }
    if (s.documentSource === "generated" && s.documentId) { const ref = await fetchDocRef("generated", s.documentId); if (!ref) return false; openRef(ref, { citation, opener }); return true; }
    if (s.href && /^\/files\//.test(s.href)) { openRef(aipDocRef(s.href, s.label), { citation, opener }); return true; }
    return false;
  }, [openRef]);

  /** §V6 — from a verbatim block: open the authoritative document and check the quoted clause against the file. */
  const openVerbatim = useCallback(async (r: VerbatimRecord & { documentId?: string | null }, conversationId: string | null, opener?: HTMLElement | null) => {
    if (!r.documentId) return false;
    const ref = await fetchDocRef("knowledge", r.documentId); if (!ref) return false;
    openRef(ref, { citation: { k: 0, page: r.page ?? null, span: null, verbatim: { text: r.text, recordId: r.id }, conversationId }, opener });
    return true;
  }, [openRef]);

  /** §V8 — an agent table result in its own tab. */
  const openTable = useCallback((t: TableData, opener?: HTMLElement | null) => {
    const label = t.title ?? `${t.rows.length} rows`;
    openRef({ key: `table:${t.id}`, source: "table", id: t.id, filename: `Result · ${label}`, mime: null, bytes: null, url: null, downloadUrl: null, sourceUrl: null, tier: "internal", sourceName: t.footer?.openLabel ?? "Agent result", table: t }, { opener });
  }, [openRef]);

  /** §V3 E5 — a Knowledge base row: panel closed, "Ask about this document" in the header. */
  const openKnowledge = useCallback(async (id: string, opener?: HTMLElement | null) => {
    const ref = await fetchDocRef("knowledge", id); if (!ref) return false;
    openRef(ref, { opener, panelClosed: true, from: "Knowledge base" }); return true;
  }, [openRef]);

  return { openRef, openDocumentResult, openGenerated, openAttachment, openCitation, openVerbatim, openTable, openKnowledge, hasViewer: Boolean(viewer) };
}
