-- Help Centre (console + developer inbox + Telegram mini app).
-- One thread vocabulary across every surface: the reference (RPT-xxxx / CHT-xxxx),
-- the type chip, and the four status words the wall Reports page already uses.
-- Access is service-role only (the API layer is the access control, like bug_reports);
-- RLS is enabled with no policies so anon/authenticated PostgREST access is denied.

create extension if not exists pgcrypto;

create table if not exists public.help_threads (
  id uuid primary key default gen_random_uuid(),
  ref_no bigint generated by default as identity (start with 2100) unique,
  -- The shared key that appears identically on every surface.
  reference text generated always as (
    (case when type = 'chat' then 'CHT-' else 'RPT-' end) || lpad(ref_no::text, 4, '0')
  ) stored,
  type text not null check (type in ('bug', 'request', 'question', 'urgent', 'chat')),
  title text not null,
  -- Exactly the Reports page vocabulary. A thread and a report row must never disagree.
  status text not null default 'untouched'
    check (status in ('untouched', 'under_process', 'done', 'impossible')),
  status_reason text,          -- required by the API before status may become 'impossible'
  user_id uuid not null,
  user_email text,
  user_name text,
  -- Auto-collected context: six read-only fields in fixed order
  -- (page, role, browser, viewport, services, lastRequest).
  context jsonb not null default '{}'::jsonb,
  -- Presence is a chat/urgent concept; reports never carry it.
  presence text not null default 'none'
    check (presence in ('none', 'not_notified', 'notified', 'joining', 'present', 'no_answer')),
  presence_at timestamptz,
  linked_from uuid references public.help_threads (id),  -- reopening a Done thread files a linked report
  telegram_chat_id text,
  telegram_message_id bigint,
  ops_last_read_at timestamptz,
  dev_last_read_at timestamptz,
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status_updated_at timestamptz not null default now(),
  status_updated_by text
);

create index if not exists idx_help_threads_user_created
  on public.help_threads (user_id, created_at desc);
create index if not exists idx_help_threads_status_last_message
  on public.help_threads (status, last_message_at desc);
create unique index if not exists idx_help_threads_reference
  on public.help_threads (reference);

-- Messages: someone speaking. Structured blocks, never rendered HTML,
-- so the console and the mini app both render natively.
create table if not exists public.help_messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.help_threads (id) on delete cascade,
  author text not null check (author in ('ops', 'developer')),
  author_id uuid,
  author_name text,
  blocks jsonb not null default '[]'::jsonb,
  client_key text,             -- offline-queue dedupe: same key never inserts twice
  created_at timestamptz not null default now()
);

create index if not exists idx_help_messages_thread_created
  on public.help_messages (thread_id, created_at asc);
create unique index if not exists idx_help_messages_client_key
  on public.help_messages (thread_id, client_key) where client_key is not null;

-- System events: never messages, rendered as a single line with a dot,
-- so they can never be mistaken for someone speaking.
create table if not exists public.help_events (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.help_threads (id) on delete cascade,
  kind text not null check (kind in
    ('opened', 'status_changed', 'joined', 'chat_closed', 'nudged', 'linked_report', 'presence_changed')),
  payload jsonb not null default '{}'::jsonb,
  actor text,
  created_at timestamptz not null default now()
);

create index if not exists idx_help_events_thread_created
  on public.help_events (thread_id, created_at asc);

-- Attachments: uploaded before the thread exists (bound on send), stored on the
-- shared /storage volume, served only through the authenticated attachment route.
create table if not exists public.help_attachments (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid references public.help_threads (id) on delete set null,
  message_id uuid references public.help_messages (id) on delete set null,
  owner_id uuid not null,
  name text not null,
  size bigint not null,
  mime text not null,
  is_image boolean not null default false,
  storage_key text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_help_attachments_thread
  on public.help_attachments (thread_id);
create index if not exists idx_help_attachments_owner_created
  on public.help_attachments (owner_id, created_at desc);

-- Saved replies (developer side). sets_status pairs the reply with a status change.
create table if not exists public.help_saved_replies (
  id uuid primary key default gen_random_uuid(),
  text text not null,
  sets_status text check (sets_status in ('untouched', 'under_process', 'done', 'impossible')),
  use_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The five starters from the design; edits/deletes are the developer's.
insert into public.help_saved_replies (text, sets_status)
select v.text, v.sets_status from (values
  ('Looking at it now.', 'under_process'),
  ('Fixed — it will be live in the next deploy.', 'done'),
  ('Can you send a screenshot of the console?', null),
  ('Which ICAO and what time (UTC) did it happen?', null),
  ('Not possible with the data we get from EAD — here is why:', 'impossible')
) as v(text, sets_status)
where not exists (select 1 from public.help_saved_replies);

-- Service-role only: RLS on, no policies.
alter table public.help_threads enable row level security;
alter table public.help_messages enable row level security;
alter table public.help_events enable row level security;
alter table public.help_attachments enable row level security;
alter table public.help_saved_replies enable row level security;
