// Generates the extension's icons from the repo's own vector marks — never from a bitmap, never redrawn.
//   emblem : the Clearway emblem, the first path of public/clearway-logo.svg (the round glyph before the wordmark)
//   ring   : the agent ring mark, public/icons/ring-mark.svg (console sidebar icon, orb, email header)
// Each size is rendered separately by Chromium from the SVG at that exact pixel size, so 16 px is drawn at
// 16 px, not scaled down from 128. Colours come from shared/design-tokens.json. The mark sits on a white disc
// so it stays visible on a dark Chrome theme. A pale set (40 % opacity) is the signed-out state.
//   node extension/scripts/make-icons.mjs [emblem|ring]   → extension/public/icons/app-*.png, app-off-*.png
//   node extension/scripts/make-icons.mjs --preview <dir> → both candidates at every size, for comparison
import fs from "node:fs"; import path from "node:path";
import { chromium } from "../../node_modules/playwright/index.mjs";
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../..");
const tokens = JSON.parse(fs.readFileSync(path.join(root, "shared/design-tokens.json"), "utf8"));
const INK = tokens.color.text, BLUE = tokens.color.primary, WHITE = tokens.color.card;
const SIZES = [16, 32, 48, 128];

const logo = fs.readFileSync(path.join(root, "public/clearway-logo.svg"), "utf8");
const emblemPath = /<path[^>]*\sd="([^"]+)"/.exec(logo)[1]; // first path = the emblem (viewBox 0 0 243.2 243.2)
const ring = fs.readFileSync(path.join(root, "public/icons/ring-mark.svg"), "utf8");
const ringInner = ring.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");

const svgFor = (kind, size) => kind === "emblem"
  // Emblem: white disc behind the glyph (same circle as its outline), glyph in ink.
  ? `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="-4 -4 251.2 251.2"><circle cx="121.6" cy="121.6" r="121.6" fill="${WHITE}"/><path d="${emblemPath}" fill="${INK}"/></svg>`
  // Ring: the ring-mark's own geometry, white inside, ink ring, dot in primary. Stroke slightly heavier at 16 px.
  : `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10.6" fill="${WHITE}"/>${ringInner.replace(/<circle cx="12" cy="12" r="9.5"\/>/, `<circle cx="12" cy="12" r="9.5" stroke="${INK}" stroke-width="${size <= 16 ? 3 : 2.25}" fill="none"/>`).replace(/fill="currentColor"/, `fill="${BLUE}"`)}</svg>`;

async function render(page, kind, size, opacity) {
  await page.setViewportSize({ width: size, height: size });
  await page.setContent(`<html><body style="margin:0;background:transparent"><div style="width:${size}px;height:${size}px;opacity:${opacity}">${svgFor(kind, size)}</div></body></html>`);
  return page.screenshot({ omitBackground: true, clip: { x: 0, y: 0, width: size, height: size } });
}

const browser = await chromium.launch();
const page = await browser.newPage({ deviceScaleFactor: 1 });
const args = process.argv.slice(2);
if (args[0] === "--preview") {
  const dir = args[1]; fs.mkdirSync(dir, { recursive: true });
  for (const kind of ["emblem", "ring"]) for (const s of SIZES) for (const [tag, op] of [["on", 1], ["off", 0.4]]) fs.writeFileSync(path.join(dir, `${kind}-${tag}-${s}.png`), await render(page, kind, s, op));
  console.log(`previews in ${dir}`);
} else {
  const kind = args[0] || "emblem";
  const out = path.join(root, "extension/public/icons"); fs.mkdirSync(out, { recursive: true });
  for (const s of SIZES) { fs.writeFileSync(path.join(out, `app-${s}.png`), await render(page, kind, s, 1)); fs.writeFileSync(path.join(out, `app-off-${s}.png`), await render(page, kind, s, 0.4)); }
  fs.writeFileSync(path.join(out, "SOURCE.txt"), `Generated by extension/scripts/make-icons.mjs (${kind}) from ${kind === "emblem" ? "public/clearway-logo.svg" : "public/icons/ring-mark.svg"}. Do not edit by hand.\n`);
  console.log(`wrote ${kind} icons: ${SIZES.map((s) => `app-${s}, app-off-${s}`).join("; ")}`);
}
await browser.close();
