// Writes .env.rig for the local rig from the running local Supabase stack. Contains NO production database
// credentials: the Supabase URL and keys are the local stack's. Model keys (Bedrock, ElevenLabs, Tavily)
// are copied from .env only when a person types the phrase, because a rig that cannot call a model is useless
// — they are service keys, not the database.
import fs from "node:fs";
import { execSync } from "node:child_process";
import path from "node:path";
const here = path.dirname(new URL(import.meta.url).pathname); const root = path.join(here, "..");
const status = JSON.parse(execSync("npx --yes supabase@latest status --workdir . -o json", { cwd: here, stdio: ["ignore", "pipe", "ignore"] }).toString());
const get = (...names) => { for (const n of names) if (status[n]) return status[n]; throw new Error(`supabase status lacks ${names.join("/")}`); };
const lines = [
  "# Clearway test rig — generated by rig/make-env.mjs. Local Supabase only; never production.",
  `NEXT_PUBLIC_SUPABASE_URL=${get("API_URL")}`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${get("ANON_KEY")}`,
  `SUPABASE_SERVICE_ROLE_KEY=${get("SERVICE_ROLE_KEY")}`,
  "DISABLE_AUTH_FOR_TESTING=true",
  "AGENT_TEST_ROLE=developer",
  "DEVELOPER_EMAILS=rig-test@rig.invalid",
  "ADMIN_EMAILS=rig-test@rig.invalid",
  "NEXT_PUBLIC_SITE_URL=http://127.0.0.1:3999",
  "PORTAL_SITE_URL=http://127.0.0.1:3999",
  "PORTAL_BASE_URL=http://127.0.0.1:3999",
  "DIGITAL_WALL_INTERNAL_URL=http://127.0.0.1:5199",
  "AGENT_WALL_EVENTS_SECRET=rig-local-wall-events-secret",
  `STORAGE_ROOT=${path.join(here, ".scratch", "storage")}`,
  `CACHE_ROOT=${path.join(here, ".scratch", "cache")}`,
  "NODE_ENV=production",
];
const MODEL_KEYS = ["AWS_REGION", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "BEDROCK_REGION", "BEDROCK_GUARDRAIL_ID", "BEDROCK_GUARDRAIL_VERSION", "ELEVENLABS_API_KEY", "TAVILY_API_KEY", "CHECKWX_API_KEY"];
const PHRASE = "yes, copy model keys into the rig";
if (process.env.RIG_COPY_MODEL_KEYS === PHRASE && fs.existsSync(path.join(root, ".env"))) {
  const src = Object.fromEntries(fs.readFileSync(path.join(root, ".env"), "utf8").split("\n").filter((l) => /^[A-Z_]+=/.test(l)).map((l) => { const i = l.indexOf("="); return [l.slice(0, i), l.slice(i + 1)]; }));
  for (const k of MODEL_KEYS) if (src[k]) lines.push(`${k}=${src[k]}`);
  lines.push("# model keys above copied from .env (service keys, not the database)");
} else lines.push(`# no model keys: run with RIG_COPY_MODEL_KEYS="${PHRASE}" to copy Bedrock/ElevenLabs keys from .env`);
fs.writeFileSync(path.join(root, ".env.rig"), lines.join("\n") + "\n", { mode: 0o600 });
console.log(`wrote .env.rig (${lines.length} lines) → ${get("API_URL")}`);
