// The seed for public.permission_grants, generated from the catalogue's defaults: one row per role × action, allowed
// or not, so "no row" always means an action added later that nobody has decided on yet. docs/supabase-permissions.sql
// carries this block verbatim; lib/permissions/check.mjs fails if the two ever differ.
//   node lib/permissions/sql.mjs      prints the block
import { ACTIONS, ROLES, defaultGrants } from "./catalogue.mjs";

export const SEED_BEGIN = "-- BEGIN SEED (generated by `node lib/permissions/sql.mjs`; do not edit by hand)";
export const SEED_END = "-- END SEED";

export function seedSql() {
  const d = defaultGrants();
  const rows = [];
  for (const action of ACTIONS.keys()) for (const role of ROLES) rows.push(`  ('${role}', '${action}', ${d[role].has(action)})`);
  return [
    SEED_BEGIN,
    "insert into public.permission_grants (role, action, allowed, updated_by_email) select r, a, al, 'default (seed)' from (values",
    rows.join(",\n"),
    ") as v(r, a, al)",
    "on conflict (role, action) do nothing;",
    SEED_END,
  ].join("\n");
}

if (import.meta.url === `file://${process.argv[1]}`) console.log(seedSql());
