-- Dispatcher agent, Part 5: generated files and email.
--
-- Two logs, because they answer different questions. agent_generated_files
-- answers "where did this document come from"; agent_email_log answers "who
-- sent what to whom, and what did the provider say". A silently swallowed email
-- failure has cost this project weeks, so the provider's own error is a column
-- rather than a line in a container log nobody reads.
--
-- Run in the Supabase SQL editor. Idempotent.

begin;

create table if not exists public.agent_generated_files (
  id uuid primary key default gen_random_uuid(),
  user_id uuid null,
  user_email text null,
  conversation_id uuid null,
  kind text not null,                   -- pdf | docx | xlsx | csv
  filename text not null,
  storage_key text not null,            -- under STORAGE_ROOT, never the root volume
  mime text null,
  bytes bigint null,
  sha256 text null,
  title text null,
  -- What went INTO the file: tool calls, document ids, tier-1 record ids. This
  -- is what makes a generated briefing auditable months later.
  sources jsonb not null default '[]',
  generated_ms integer null,
  created_at timestamptz not null default now()
);

create index if not exists idx_agent_files_user on public.agent_generated_files (user_id, created_at desc);
create unique index if not exists idx_agent_files_storage on public.agent_generated_files (storage_key);

create table if not exists public.agent_email_log (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  user_email text null,
  conversation_id uuid null,
  recipients text[] not null default '{}',
  -- Recorded separately: an external send is the one that needed a human to
  -- confirm it, and "who did we mail outside the company" is asked on its own.
  external_recipients text[] not null default '{}',
  subject text not null,
  attachments jsonb not null default '[]',
  status text not null check (status in ('sent', 'failed', 'blocked')),
  provider_id text null,                -- Resend's message id
  provider_error text null,             -- the provider's OWN words, never a paraphrase
  reference text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_agent_email_user on public.agent_email_log (user_id, created_at desc);
create index if not exists idx_agent_email_status on public.agent_email_log (status, created_at desc);

alter table public.agent_generated_files enable row level security;
alter table public.agent_email_log enable row level security;

commit;
