-- PDF download timing stats — used to show estimated download time.
-- Run in Supabase SQL editor.

create table if not exists public.pdf_download_stats (
  id bigint generated by default as identity primary key,
  icao text not null,
  source text not null,       -- 'ead' | 'scraper' | 'usa' | 'asecna'
  duration_ms integer not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_pdf_download_stats_icao
  on public.pdf_download_stats(icao, created_at desc);

create index if not exists idx_pdf_download_stats_source
  on public.pdf_download_stats(source, created_at desc);

-- Public insert — no auth needed, these are anonymous timing metrics.
alter table public.pdf_download_stats enable row level security;

create policy "pdf_download_stats_insert_anon"
on public.pdf_download_stats
for insert
to anon, authenticated
with check (true);

-- Service role reads for the estimate API (bypasses RLS).
