-- Dispatcher agent, Part 1: access allowlist, kill switch and audit log.
-- Run in the Supabase SQL editor. Idempotent.
--
-- Access model, enforced by the API layer (RLS denies PostgREST outright, as
-- with the Help Centre tables — every caller is authenticated by the service
-- first and reads go through the service-role key):
--   * agent_access      — who may use the agent at all. Managed by DEVELOPERS.
--   * agent_settings    — the global kill switch. One row, id = 'global'.
--   * agent_audit_log   — every agent request and every access change.

begin;

-- 1) Allowlist. One row per grant; revocation is a soft close (revoked_at set)
-- so the history of who had access, when, and who granted it survives.
create table if not exists public.agent_access (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  user_email text null,
  granted_by uuid null,
  granted_by_email text null,
  granted_at timestamptz not null default now(),
  revoked_at timestamptz null,
  revoked_by uuid null,
  revoked_by_email text null,
  note text null
);

-- At most one ACTIVE grant per user; revoked rows accumulate as history.
create unique index if not exists idx_agent_access_active_user
  on public.agent_access (user_id) where revoked_at is null;
create index if not exists idx_agent_access_user on public.agent_access (user_id);
create index if not exists idx_agent_access_granted_at on public.agent_access (granted_at desc);

-- 2) Global kill switch. Independent of the allowlist: when disabled, nobody
-- gets the agent regardless of grants. One switch beats twelve revocations.
create table if not exists public.agent_settings (
  id text primary key,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid null,
  updated_by_email text null,
  reason text null
);

insert into public.agent_settings (id, enabled, reason)
values ('global', true, 'Initial state')
on conflict (id) do nothing;

-- 3) Audit log. Written from the first commit. `kind` covers both agent
-- traffic and access administration so one feed answers "what happened".
create table if not exists public.agent_audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  kind text not null,
  user_id uuid null,
  user_email text null,
  actor_id uuid null,            -- who performed an admin action (grant/revoke/kill switch)
  actor_email text null,
  conversation_id text null,
  model_tier text null,          -- router | fast | standard | reasoning | extraction | embeddings | rerank
  model_id text null,            -- the concrete Bedrock id actually invoked
  tool_name text null,
  tool_args jsonb null,
  tool_result jsonb null,
  confirmation_status text null, -- pending | confirmed | rejected | not_required
  success boolean null,
  error text null,
  latency_ms integer null,
  input_tokens integer null,
  output_tokens integer null,
  detail jsonb null
);

create index if not exists idx_agent_audit_created_at on public.agent_audit_log (created_at desc);
create index if not exists idx_agent_audit_user on public.agent_audit_log (user_id, created_at desc);
create index if not exists idx_agent_audit_conversation on public.agent_audit_log (conversation_id, created_at);
create index if not exists idx_agent_audit_kind on public.agent_audit_log (kind, created_at desc);

-- 4) RLS on, with no permissive policies: PostgREST (anon/authenticated) can
-- read nothing. Access is exclusively through the service-role key behind an
-- authenticated API, matching the Help Centre tables.
alter table public.agent_access enable row level security;
alter table public.agent_settings enable row level security;
alter table public.agent_audit_log enable row level security;

commit;
