-- Create per-user search analytics table + RLS policies
-- Run in Supabase SQL editor.

create table if not exists public.search_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  query text not null,
  result_count int null,
  source text null,
  created_at timestamptz not null default now()
);

alter table public.search_events enable row level security;

-- Users can insert their own events
create policy "search_events_insert_own"
on public.search_events
for insert
to authenticated
with check (auth.uid() = user_id);

-- Users can read their own events
create policy "search_events_select_own"
on public.search_events
for select
to authenticated
using (auth.uid() = user_id);

